# Generated by Django 4.2.7 on 2023-12-28 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='slug',
            field=models.SlugField(default='', verbose_name='url'),
        ),
        migrations.AlterField(
            model_name='products',
            name='popularity',
            field=models.BooleanField(verbose_name='فعال/غیرفعال'),
        ),
    ]
